export const termsAndConditions = {
  en: {
    title: "Terms and Conditions",
    mainTitle: "Company Terms and Conditions",
    description:
      "These Terms and Conditions govern the relationship between you and/or your company and Leago Saudi Information Technology Company, a company licensed by the Saudi Ministry of Commerce, and cover your use and access to the Platform and/or Application. By accessing and using the Platform and/or Application, you acknowledge that you have read, understood, and agreed to be bound by these Terms and Conditions, as amended from time to time. If you do not agree to these Terms and Conditions, you must immediately cease using or accessing the Platform and/or Application. If you are using the Platform on behalf of a third party including, but not limited to, a business entity, you warrant that you are authorized and have the authority to bind that third party to these Terms and Conditions.",
    definitionsTitle: "1. Definitions:",
    definitions: `a. The following terms are used in the context of these Terms and Conditions and have specific meanings.
b. "Account" means the account required from users to register through the Application and/or Platform to use the Services, including the documents required to complete account registration.
c. "Additional Fees" means fees that the Client may incur as a result of the Client's use of a Vehicle, including but not limited to traffic and parking fines, toll fees, fuel fees, excess mileage fees, insurance premium, and early termination penalty fees (as described in Clause 8).
d. "Agreement" and "Terms and Conditions" collectively mean all provisions, terms, and notices contained or referenced in this document (as amended from time to time) and all other Leago rules and policies available on the Platform (including but not limited to the Privacy Policy and guidelines and procedures that may be published from time to time on the Platform).
e. "Application" means the mobile application provided by Leago that connects Clients with Vendors for car rental.
f. "Client", "you", and "your" collectively mean a person or company that communicates with and/or subscribes to and/or wishes to rent a car or cars from a Vendor through the Platform and/or Application.
g. "Confirmation Order" means any and all written or electronically transmitted confirmation orders sent by Leago for car rental which may include, but not limited to, booking number, vehicle description, location, date and time of pickup, location, date and time of delivery, vendor details, payment terms, quantity, duration of car rental, and any special conditions.
h. "Confirmed Booking" means confirmation of a booking by the Vendor after receiving a car rental booking request submitted by the Client through the Platform.
i. "Content" means any content provided, created, posted, or displayed through the Platform or Application (including but not limited to any vehicle profile, text, correspondence, images, graphics, software, applications, video recordings, audio recordings, sounds, designs, features, and other materials available on the Platform). Content includes, but is not limited to, User Content that may be provided by the User.
j. "Credit Rating Authorization Letter" means the credit rating authorization letter you sign to authorize Leago to collect your credit rating in the form attached to this document in Appendix 1.
k. "Digital Wallet" means any balance held on the Platform and/or Application by Leago and linked to a User's account through which any credits due to the User can be recorded, in accordance with the provisions of Clause 5.
l. "Discount Amount" means the amount or value of the discount applied to the Rental Payment as shown in the Confirmation Order and/or invoice.
m. "Early Termination Penalty Fee" means the penalty fee payable by the Client in case of early termination of the Vehicle Rental Agreement by the Client (as provided in Clause 8-1 (8)).
n. "Rental Payment" means the car rental amount as shown in the Confirmation Order and/or Vehicle Rental Agreement and charged to Clients through the Platform.
o. "Mid-Month Return Fee" means a fixed fee payable by the Client in case of early return of the Vehicle (as described in Clause 9-6), which may be determined by Leago from time to time and notified on the Platform and/or Application.
p. "Platform" means any online tool provided and/or processed and/or maintained by Leago (including but not limited to through the Leago application, website, all subpages and subdomains, and all content, services, and products available on or through the Platform located at: https://www.legao.org or any other relevant domain that enables access to or facilitates the provision of Services).
q. "Privacy Policy" means Leago's privacy practices regarding the use of User Content, Platform, and Services available at: https://www.legao.org.
r. "Service" means the online and/or offline services provided by Leago to provide and use the technology developed by Leago for collaboration, communication, and payment between Vendors and Clients, including but not limited to access to the Leago application, online community, communication tools, and payment services.
s. "Successful Rental" means the Client's acceptance of a Confirmation Order as evidenced by the deposit or payment of all or part of the Rental Payment.
t. "Third Party Content" means any content belonging to or originating from third parties.
u. "User Content" means any content, written or otherwise, created, provided, drafted, posted, or displayed through the Platform (including but not limited to any text, correspondence, and images) by Users while using the Platform.
v. "User" means a person, company, or organization that has visited or used the Platform and/or Service. A User may be a Client, a Vendor, both, or neither.
w. "Vehicle Rental Agreement" means the agreement to be entered into between the Vendor and the Client to formalize the arrangements executed between them, which in turn defines the main terms of the transaction between them (including but not limited to description and duration of car rental, rental payment, and payment terms).
x. "Car Rental" means a Client's rental of a car from a Vendor using the Platform.
y. "Vehicle" means the Vendor's vehicle registered on the Platform that has been rented by a Client or which the Vendor has agreed to rent to the Client through the Platform, including its parts, components, accessories, and registration documents.
z. "Vendor" means a car rental company or establishment that provides Vendor services to the Client through the Platform.
aa. "Vendor Services" means any services provided by Vendors in relation to car rental as defined in the Vehicle Rental Agreement, including but not limited to providing properly functioning vehicles without damage, reporting any additional fees, and providing assistance in case of vehicle breakdown.`,
    aboutUsTitle: "2. About Leago:",
    aboutUs: `Leago is a platform that connects Vendors with Clients. Leago provides access to Leago's virtual Vendor community and easy collaboration through Leago's communication tools and secure payment tools.
2-1 You understand and agree that Vendors are not employees or agents of Leago and that any transaction and/or agreement (such as a Vehicle Rental Agreement) entered into as a result of your use of the Services, whether oral or written, is between you and the Vendor only, and Leago is not a party to it. You and the Vendor have full discretion regarding the terms of any Vehicle Rental Agreement. Aside from these Terms and Conditions, you will be required, at or around the time of vehicle pickup, to enter into a Vehicle Rental Agreement which constitutes a direct contractual relationship between the Client and the Vendor. You acknowledge and agree that in such case, Leago will not be a party to the Vehicle Rental Agreement and will not be responsible for executing the obligations of any Vehicle Rental Agreement entered into between you and any Vendor, and Leago disclaims any liability arising from or relating to any Vehicle Rental Agreement.
2-2 You agree and acknowledge that Leago does not own, sell, rent, re-rent, or lease any vehicles and that Vendors are solely responsible for car rental and that Leago acts as an intermediary between Clients and Vendors and its role is solely to facilitate the availability of Services to Clients and Vendors.
2-3 Leago does not endorse one Vendor over another for Client service. While Leago makes commercially reasonable efforts to confirm that Vendors are licensed and have the required government approvals to provide car rental service, we make no representation, warranty, or declaration regarding the licensing, ability, competence, compliance, quality, or qualifications of any Vendor. You agree and understand that it is your responsibility to inquire about and evaluate any Vendor's licensing, ability, competence, compliance, quality, or qualifications.
2-4 Although Leago requires Vendors to provide accurate information, we do not verify any alleged identity of any Vendor. Clients agree to independently research and evaluate any Vendor.
2-5 Although Leago requires Vendors to have commercial insurance and/or professional liability insurance, Leago does not represent or guarantee that Vendors have any commercial insurance and/or professional liability insurance, and Leago makes no representation or warranty regarding the adequacy of such commercial insurance and/or professional liability insurance.
2-6 You understand and acknowledge that the car rental price offered to you depends on your credit rating as available from the Saudi Credit Bureau (SIMAH). By accepting our Terms and Conditions, you authorize us to obtain your credit rating from the Saudi Credit Bureau (SIMAH). You also authorize us to disclose your information to the Saudi Credit Bureau (SIMAH).`,
    amendmentsTermsAndConditionsTitle:
      "3. Amendments to the Terms and Conditions:",
    amendmentsTermsAndConditions: `3-1 You agree that Leago may amend this Agreement from time to time, at Leago's sole discretion. Although we will make our best efforts to inform you of any amendments to this Agreement, we will not be required to provide you with prior notice of such amendments or changes to this Agreement and your continued use of the Platform or Services will constitute your consent to such amendments or changes to the Agreement.
3-2 When making any amendment or change to this Agreement, we will publish the amended Agreement on the dedicated link available on our platform. Your continued use of the Platform and/or Service after the date of publication of a revised version of this Agreement constitutes your consent to its terms.
3-3 You agree and undertake to review our Terms and Conditions each time you visit our platform and/or before using any of the Services. If you do not agree to our Terms and Conditions, as updated from time to time, you undertake to immediately cease using our platform and/or services.`,
    registerAndClientResponsibilitiesTitle:
      "4. Client Sign-Up and Responsibilities:",
    registerAndClientResponsibilities: `4-1 If you wish to use our services, you must create a personal account including a unique username and password to access the Service. Each client is responsible for maintaining the security of their account and all activities conducted under the account and any other actions taken in relation to the account. You undertake to provide accurate and complete information, maintain and update your account information, and keep it confidential. You also agree to immediately notify Leago of any unauthorized use of the account or any other security breaches. We will not be responsible for any liabilities, losses, or damages arising from unauthorized use of your computer, mobile phone, or any other computer and/or account.
4-2 We reserve the right to suspend or terminate your account at any time, including if any user content or information provided during or after the registration process is proven to be inaccurate, false, or misleading, or to reclaim any username you create through the Services that violates this Agreement.
4-3 When using the Services, Clients undertake to provide Leago with their personal information (including name, address, email address, date of birth, driver's license data, credit card information, and phone number). You agree and accept that Leago will share any of this information with available Vendors who may be able to provide Vendor services.
4-4 Upon executing a Successful Rental, Clients agree that the car rental will be extended or modified through the Platform only, and that any other or recurring payments for the car rental will only be made through the Platform.`,
    digitalWalletTitle: "5. Digital Wallet:",
    digitalWallet: `5-1 Leago maintains, for each user account, a Digital Wallet in which any credit balance is held in accordance with the terms of this Agreement.
5-2 Any credit balance will be stored in the Digital Wallet for 60 days before expiring, and the User may use it to pay for any service provided by Leago through the Platform and/or Application.
5-3 For the avoidance of doubt, Users cannot deposit funds or credit balance in the Digital Wallet. The Digital Wallet can only be used to record and store any credit balance issued by Leago to the User in accordance with the terms of this Agreement.`,
    userBehaviorRestrictionsTitle: "6. User Behavior Restrictions:",
    userBehaviorRestrictions: `6-1 You agree that you will not, under any circumstances, transmit any content that: (1) is illegal or encourages illegal activity; or (2) defames, harasses, abuses, threatens, or incites violence against any individual or group; or (3) is political, pornographic, discriminatory, or otherwise contributes to the harm or intimidation of any individual or group based on religion, gender, sexual orientation, race, ethnicity, age, or disability; or (4) constitutes spam, unsolicited or unwanted advertising, or any other form of unauthorized solicitation; or (5) contains or establishes any viruses, worms, malware, Trojans, or any other content designed or intended to disrupt, damage, or limit the functioning of any software, hardware, or telecommunications equipment or to damage or obtain unauthorized access to any data or other information belonging to third parties; or (6) infringes any proprietary rights of any party, including patents, trademarks, trade secrets, copyrights, publicity rights, or other rights; or (7) impersonates any person or entity, including any of our employees or representatives; or (8) violates the privacy of third parties.
6-2 By accessing or using the Platform and/or Services, you acknowledge and warrant the following: (1) you have a valid driver's license in the Kingdom of Saudi Arabia; and (2) you have the authority to properly enter into and/or commit to this Agreement; and (3) your use of the Services is for legal purposes only as permitted by this Agreement; and (4) your use of the Services complies with all laws, rules, and regulations in the Kingdom of Saudi Arabia, and with all Leago policies; as amended from time to time.
6-3 You acknowledge and warrant that you are over 18 years of age. Leago does not target any content to children or teenagers under the age of 18, and we do not allow any clients under the age of 18 to use our service. Please immediately stop using the Platform if you are under this legal age.
6-4 At our discretion, we, or the technology we use, may monitor and/or record your public interactions with the Service. However, any liability, loss, or damage occurring as a result of any User interactions is your sole responsibility, as further outlined in Clauses 14 and 15 of this Agreement.
6-5 We have the right, at our sole discretion, to determine whether Client behavior is appropriate and complies with these Terms and Conditions. We also have the right to terminate or deny access to any account and service to any client for any reason, with or without prior notice.`,
    userContentTitle: "7. User Content:",
    userContent: `7-1 We are not responsible for any public display or misuse of your User Content. Users are solely responsible for the content and any damage resulting from any user content they provide, post, upload, link, or make available while using the Service. You acknowledge that any liability, loss, or damage occurring as a result of any such user content is your sole responsibility. You also undertake and agree to compensate us and hold us (and any third parties) harmless from any liability, loss, or damage that may occur as a result of any user content.
7-2 From time to time, Clients may provide feedback about Vendors; such feedback does not constitute a guarantee, representation, or expectation regarding the results of any future Vendor service. Leago will not be obligated to display such feedback and may remove such ratings at any time at its sole discretion. Leago will not bear any responsibility or obligation of any kind for any feedback you encounter on or through the Platform, and any use of or reliance on such feedback is at your own risk.
7-3 User Content posted on the Platform, such as blog posts or feedback, is provided for informational purposes only, without any warranty that such content is sound, correct, or accurate.
7-4 Users acknowledge and warrant that they have the right to post all User Content they provide. Specifically, Users warrant that they have fully complied with any third-party licenses relating to User Content (if applicable), and have taken all necessary steps to convey any required terms to end users.
7-5 Users agree and acknowledge that Leago has the right, at its sole discretion, to display and monitor any User Content, determine whether any User Content is appropriate or does not comply with these Terms and Conditions, or refuse or remove any User Content that, in Leago's reasonable opinion, violates any Leago policy or is considered - in any way - harmful, inappropriate, or unwanted. Users also agree that Leago has the right to perform formatting, editing, and make changes to User Content or the manner in which any User Content is displayed on the Platform.
7-6 Except for content originating from Leago, we do not claim ownership of any content you post, upload, or link. You retain full ownership of, control over, and responsibility for the User Content you post. By posting any content including but not limited to company images, logos, and feedback through the Platform, you expressly grant Leago and our successors a worldwide, sublicensable, fully paid, royalty-free, and non-exclusive license to use, re-issue, display, modify, adapt, distribute, and perform the content in connection with Leago's commercial purpose. This license does not grant Leago the right to sell User Content or distribute it outside our platform.`,
    additionalFeesAndRentalPaymentTitle:
      "8. Additional Fees And Rental Payment:",
    additionalFeesAndRentalPayment: `8-1 The Client agrees and accepts that Additional Fees are calculated as follows:
(1) For traffic and/or parking fines, an administrative fee of 16% is applied. As such, the Client undertakes to pay the applicable traffic fines and/or parking fines and an amount equal to 16% of the traffic fines and/or parking fines as administrative fees.
(2) For fuel fees, an administrative fee of 20% is applied. As such, the Client undertakes to pay the applicable fuel fees and an amount equal to 20% of the fuel fees as administrative fees.
(3) For any excess miles, an administrative fee of 45 halalas per kilometer is applied. As such, the Client undertakes to pay 45 halalas per kilometer as administrative fees if the total kilometers driven exceeds the contractually allowed limit each month.
(4) Insurance premium is calculated per vehicle.
(5) Any additional fees incurred under this Clause 8-1 must be paid immediately after Leago notifies the Client of the additional costs incurred.
(6) In the event that the Client defaults on payment obligations under this Agreement and/or the Vehicle Rental Agreement and/or fails to respond to Leago's notices regarding any late payment, the Vehicle will be repossessed by the Vendor with all applicable fees and charges charged to the Client. The Vendor will contact the Client regarding the vehicle repossession process, and the Client cooperates with the Vendor accordingly. The Client will continue to bear any applicable fees under this Agreement and/or the Vehicle Rental Agreement until the Vehicle is successfully returned to the Vendor. If the Client does not cooperate and/or deliver the Vehicle to the Vendor on time, the Vendor and Leago have the right to disable and/or track the Vehicle and/or involve third parties or competent authorities as appropriate (such as the police). If a vehicle is repossessed under this Clause 8-1-(7) (before the expiration of the Vehicle Rental Agreement term), any unused days already paid for by the Client will be added to the Client's Digital Wallet on a pro-rata basis to compensate for any amount due to the Client. If there is any outstanding amount owed by the Client to Leago and/or the Vendor, the Client's responsibility to pay that outstanding amount continues to apply. Leago reserves the right to repossess the Vehicle. Any unused days will be classified as a credit balance added to the Client to compensate for any amount due. Any remaining amount will remain payable by the Client.
(7) In case of early termination by the Client of the Vehicle Rental Agreement, the Client agrees to be charged an Early Termination Penalty Fee, plus a one-time administrative fee of SAR 70. The Client further agrees and acknowledges that the Early Termination Penalty Fee will be calculated as follows:
1. In case of early termination by the Client of a Vehicle Rental Agreement entered into for more than 30 days, the Early Termination Penalty Fee amount shall be equal to the Discount Amount applied multiplied by the number of months (or part thereof) during which the Vehicle was in the Client's possession.
2. In case of early termination by the Client of a Vehicle Rental Agreement entered into for up to 30 days, the Client agrees that the Client is not entitled to any refund and the Rental Payment corresponding to the remaining days of the car rental is deemed due and payable as an Early Termination Penalty Fee.
8-2 Clients understand and acknowledge that Additional Fees are subject to change from time to time and may be specifically clarified in the Confirmation Order. If there is any conflict or contradiction between the Additional Fees set forth in Clause 8-1 above and the Additional Fees set forth in the Confirmation Order, the Additional Fees set forth in the Confirmation Order shall prevail.
8-3 Clients must pay the Rental Payment to Leago on a monthly basis, as specified in the Confirmation Order and/or Vehicle Rental Agreement.
8-4 Clients agree that they will pay the Rental Payment and Additional Fees (if any) through the Platform or Application only, including recurring payments as well as subsequent transactions not necessarily related to the initial car rental.
8-5 Clients are responsible for taxes (VAT) as applicable, any processing fees associated with their use of the Services and car rental, and any credit card fees and bank transaction fees (if any).
8-6 Leago accepts payment by credit card and debit card, including but not limited to Visa and Mastercard. Clients may make payments in the currency listed in the Confirmation Order they receive. Clients hereby authorize Leago to charge their credit card for any Rental Payment and Additional Fees (if any), as well as any other recurring payments or amounts due as part of our services. By accepting our Terms and Conditions, Clients agree that they authorize Leago to automatically collect fees from them for any Rental Payment and Additional Fees (if any), as well as any other recurring payments or amounts (as applicable), without the need for any additional notice or consent. Clients are responsible for providing complete and accurate billing information to Leago and notifying Leago of any changes to such information.
8-7 All payments made online are also subject to the terms and conditions of the relevant merchant service provider. Please review the merchant service provider's terms and conditions and privacy policy before entering into any transaction. You must retain a copy of the transaction records.
8-8 Leago will not deal with or provide any services to countries subject to the Office of Foreign Assets Control and sanctioned countries.
8-9 Leago will provide you, directly or through its merchant service provider, with electronic payment confirmation immediately after successful completion of payment through the Platform. Leago will also provide you with an invoice issued by the Vendor for your review and reference regarding the Rental Payment and Additional Fees (if any) upon receipt of any such payments.`,
    cancellationOfConfirmedBookingAndEarlyReturnsTitle:
      "9. Cancellation Of Confirmed Booking And Early Returns:",
    cancellationOfConfirmedBookingAndEarlyReturns: `Cancellation of Confirmed Bookings:
9-1 Clients agree and accept that a Confirmed Booking will be valid for 24 hours from the Vendor's confirmation, after which it will be automatically cancelled.
9-2 Clients must notify Leago directly of all cancellations of Confirmed Bookings. If a Confirmed Booking is cancelled by the Client with at least 12 hours' notice before vehicle delivery, the cancellation shall be executed without penalty and the Rental Payment (or part thereof) received by Leago will be refunded to the Client's Digital Wallet, subject to any related costs, including but not limited to any bank transfer fees or credit card fees.
9-3 If a Confirmed Booking is cancelled by the Client less than 12 hours before vehicle delivery, an amount equal to 25% of the Rental Payment will be charged to the Client and the remaining amount (subject to any related costs, including but not limited to any bank transfer fees or credit card fees) will be refunded to the Client's Digital Wallet.
9-4 If the Client, within 7 days of the agreed delivery date, notifies Leago of their inability to receive the Vehicle, only an amount equal to 50% of the Rental Payment will be charged to the Client and the remaining amount (subject to any related costs, including but not limited to any bank transfer fees or credit card fees) will be refunded to the Client's Digital Wallet.
9-5 If the Client, after 7 days from the agreed delivery date, notifies Leago or fails to notify of their inability to receive the Vehicle, the full Rental Payment will be charged to the Client and they will not be entitled to any refund.
Early Returns:
9-6 The Client may return a vehicle before the expiration of the Vehicle Rental Agreement term. The applicable fees for doing so will depend on whether the Client wishes to return the Vehicle on, before, or after the next monthly payment due date as specified in the Confirmation Order and/or Vehicle Rental Agreement, and whether any Early Termination Penalty Fees apply as specified in Clause 8-1 (8). Any fees associated with early return are payable at the time the Client confirms the early return. Early returns are subject to the following conditions:
9-6-1 If the Client wishes to return the Vehicle on the next monthly payment due date, any applicable Early Termination Penalty Fees will be charged to the Client.
9-6-2 If the Client wishes to return a vehicle before the next monthly payment due date, the Client will bear (1) the Mid-Month Return Fee; and (2) any applicable Early Termination Penalty Fees. If the Client has used the Vehicle for more than 30 days, the credit for any unused days already paid for by the Client will be added to the Client's Digital Wallet upon successful return of the Vehicle. If the Client has used the Vehicle for less than 30 days, no unused days will be refunded to the Client or added to the Client's Digital Wallet.
9-6-3 If the Client wishes to return a vehicle used for up to 15 days after the next monthly payment due date, the Client will bear: (1) on a pro-rata basis, the cost of the number of days between the date the next monthly payment was due and the date the Client wishes to return the Vehicle; and (2) the Mid-Month Return Fee; and (3) any applicable Early Termination Penalty Fees.
9-6-4 If the Client wishes to return a vehicle more than 15 days after the next monthly payment due date, the Client will bear: (1) the next month's Rental Payment as specified in the Confirmation Order and/or Vehicle Rental Agreement; and (2) the Mid-Month Return Fee; and (3) any applicable Early Termination Penalty Fees. The value of any unused days for the following month will be added to the Client's Digital Wallet upon successful return of the Vehicle.
9-7 For the avoidance of doubt, Clients agree and acknowledge that any refunded funds will be added to the Client's Digital Wallet and not to the Client's bank account or credit card.
9-8 Leago may, at any time and without prior notice, use any balance in the Client's Digital Wallet to offset any amounts due under this Agreement and/or any Vehicle Rental Agreement.
9-9 Clients expressly release Leago from any and all liabilities related to car rental. Clients agree and acknowledge that Leago is not responsible for resolving any disputes between Clients and Vendors, whether related to cancellation of a confirmed booking, implementation of any changes to a confirmed booking, or otherwise, and that Leago exempts itself from any and all liabilities in this regard. If you have any inquiries about cancellations or bookings, please contact us at support@legao.com.sa or through the Platform.
9-10 Clients agree and acknowledge that Rental Payments are subject to the Vehicle Rental Agreement and under no circumstances shall Leago be responsible for refunding Rental Payments and Additional Fees.`,
    thirdPartyContentTitle: "10. Third Party Content:",
    thirdPartyContent: `10-1 By using the Service, Clients will be able to access Third Party Content and the Client's use of the Service constitutes Leago's consent to provide Third Party Content to that Client. Clients acknowledge and accept all responsibilities and bear all risks arising from their use of Third Party Content.
10-2 As part of the Service, Leago may provide you with convenient links to third party platform(s) as well as other forms of Third Party Content. These links are provided as a courtesy to Service subscribers. We have no control over third party platforms or content, promotions, materials, information, goods, or services available thereon. We are not responsible for any Third Party Content accessed through our platform. If you decide to leave the Platform and access Third Party Content, you do so at your own risk and you should be aware that our Terms and Conditions and policies no longer apply to you.
10-3 This Agreement does not authorize you to distribute, publicly display, present, make available, alter, or otherwise use any Third Party Content.`,
    intellectualPropertyTitle: "11. Intellectual Property:",
    intellectualProperty: `11-1 Leago retains ownership of all intellectual property rights of any kind related to the Platform and Service, including applicable copyrights, patents, trademarks, and other proprietary rights. Trademarks, service marks, graphics, and other logos used in connection with the Platform and Service may be trademarks of third parties. This Agreement does not transfer from us to you any intellectual property of Leago or third party intellectual property, and all rights, titles, and interests in such property (as between the parties) will remain ours alone. We reserve all rights not expressly granted to you under this Agreement.
11-2 Specifically, Leago legao.com.sa and all other trademarks that appear or are displayed or used on the Platform from time to time or as part of the Service are registered trademarks of Leago and may not be copied, downloaded, re-issued, used, modified, or distributed in any form without prior written permission from Leago.
11-3 If you believe that any material at or associated with Leago infringes your copyright, please notify us. We will terminate a User's access to and use of the Platform if the User is discovered and identified, under appropriate circumstances, as repeatedly infringing the copyrights or other intellectual property rights of Leago or others without obtaining the necessary rights and permissions.`,
    emailsTitle: "12. Emails:",
    emails:
      "We use email and electronic means to stay in touch with our clients. For contractual purposes, Clients agree: (1) to receive communications from Leago in electronic form via the email address they have sent or via the Platform; and (2) further agree that all terms, conditions, agreements, notices, disclosures, and other communications that Leago provides to them electronically satisfy any legal requirements that such communications would satisfy if they were in physical or traditional written form; and (3) without prejudice to Clauses 12(1) and 12(2), Clients undertake to comply with Clause 16-5 for any notification purposes.",
    terminatingContractTitle: "13. Terminating Contract:",
    terminatingContract: `13-1 If you wish to terminate this Agreement, you may simply stop using the Leago platform. If you wish to delete your account data, please contact Leago at support@legao.com.sa or through the Platform. We will retain and use your information as necessary to fulfill our legal obligations, resolve disputes, and enforce our agreements, and will delete your entire profile to the fullest extent possible (if applicable).
13-2 Users may delete their accounts using the Platform or Application if they have not used their accounts to obtain car rental, or once 60 days have passed since the successful return of the last vehicle rented by the User, if they have previously obtained car rental. Notwithstanding any provision to the contrary, Users agree and acknowledge that Leago reserves the right to disable a User's ability to delete their account if the User has any outstanding payments due to Leago or any Vendor under this Agreement and/or the Vehicle Rental Agreement.
13-3 Leago may terminate your access to all or any part of the Platform at any time immediately, with or without cause, with or without notice.
13-4 Termination of your relationship with Leago does not affect your relationship with any Vendor you have retained through the Leago Service. All legal, contractual, and moral duties, obligations, and liabilities remain in effect after termination of the Leago relationship.
13-5 All provisions of this Agreement that by their nature should survive termination will remain in effect including, but not limited to, ownership provisions, warranty disclaimers, indemnifications, and limitations of liability.`,
    disclaimerOfWarrantiesTitle: "14. Disclaimer Of Warranties:",
    disclaimerOfWarranties: `14-1 Leago makes no representation or warranty that the information we provide or provided through the Service is accurate, reliable, or correct; or that the Service will meet your requirements; or that the Service will be available at any particular time or location, or that the Service will operate in an uninterrupted manner or be secure; or that any defects or errors will be corrected; or that the Service is free of viruses or other harmful elements. You bear full responsibility and risk arising from loss resulting from your use of information, content, or other materials obtained from the Vendor or Service.
14-2 You are solely responsible for all correspondence and communications with Vendors, as applicable, and with other persons with whom you communicate or interact as a result of your use of the Services. You acknowledge that Leago is not required to check or investigate the background of any Vendors or car rental, and Leago makes no attempt to verify Vendor data. Leago makes no representations or warranties regarding the execution of car rental. Leago does not control or guarantee the existence, quality, authenticity, safety, or legality of any car rental advertised by Vendors; or the ability of Vendors to execute car rental; or that Vendor service will be available at any particular time or location. Leago does not represent or warrant that any car rental offered through the Platform will meet Client requirements. You agree to take reasonable precautions in all correspondence and communications with Vendors, and with other persons with whom you communicate or interact as a result of your use of the Services, especially if you decide to communicate through means other than the Services or in-person meetings.`,
    indemnificationAndCompensationTitle:
      "15. Indemnification And Compensation:",
    indemnificationAndCompensation: `15-1 You agree to indemnify, hold harmless, and protect Leago against any and all claims, demands, actions, losses, damages, assessments, fees, liabilities, costs, and expenses (including but not limited to attorneys' fees, penalties, interest, or loss of profits) made by the Vendor or any third party that may be borne or incurred at any time by Leago or assessed against it, directly or indirectly, as a result of: (1) your use of the Platform and Service or violation of this Agreement or the contractual relationship (or as a result of termination of such contractual relationship) between you and the Vendor; or (2) any injury, accident, physical damage or property damage, loss of profits, loss of property or commercial reputation or otherwise that you may cause as a result of using any service and/or car rental; or (3) defects, errors, or inaccuracies in your User Content and/or information available on or through the Platform, or (4) your unauthorized access to our servers and/or any personal information stored therein or use thereof, and/or any interruption or cessation of transmission to or from our servers, and/or any bugs, viruses, Trojans, or the like, which may be transmitted to or through the Platform, and/or (5) failure or delay in executing any transactions through the Platform and/or Services or (6) dispute, conflict, or disagreement between Users regarding any car rental or Rental Payment or Additional Fees or cancellation of any confirmed booking or car rental; or (7) failure to verify that the Vendor is legally licensed in the Kingdom of Saudi Arabia and has obtained the required government approvals to perform Vendor services.
15-2 If you have a dispute with one or more Vendors, you release Leago from any and all claims, demands, and damages (actual and consequential) or losses of every kind and nature arising from such disputes.
15-3 The Client agrees that Leago and each Vendor have - jointly and severally - the authority to bring and pursue legal actions against the Client regarding any claims, demands, actions, losses, damages, fines, fees, liabilities, costs, and expenses incurred or borne by Leago and/or the Vendor, directly or indirectly, caused by the Client as a result of the Client's use of any service and/or car rental.
15-4 The Client further agrees that if the Vendor obtains a judgment in its favor regarding a lawsuit against Leago regarding any claims, losses, damages, fines, or fees caused by the Client, Leago has the right to bring a lawsuit against the Client and recover any amount Leago had to pay to the Vendor as a result of the original lawsuit brought by the Vendor against Leago.
15-5 You agree that Leago will not under any circumstances be bound, responsible, or otherwise liable to you or to third parties for any damages or losses that may arise from: (1) disruption, interruption, or cessation of any service to maintain your access to the Platform or Services, regardless of whether the service is provided by Leago or third parties or (2) the quality, accuracy, timeliness, speed, reliability, or performance of any Vendor or Vendor service or car rental and/or the Platform or completeness, delays, breaches, defaults, or interruptions in providing car rental service or Vendor services (including but not limited to any breach committed by the Vendor of any obligation) or (3) defects, errors, or inaccuracy of any content and/or information available on or through the Platform, or (4) any unauthorized access to or use of our servers and/or any and all personal information stored therein, and/or any interruption or cessation of transmission to our servers and/or any bugs, viruses, Trojans, or the like, which may be transmitted to or through the Platform by any third party, and/or (5) any failure or delay in executing any transactions through the Platform and/or Services or, (6) any dispute, conflict, or disagreement between Users regarding any services or car rental or Rental Payment or Additional Fees or cancellation of any confirmed booking or car rental; or (7) any refunded payment or loss of profits or loss of commercial reputation (whether incurred directly or indirectly) or any injury, accident, physical damage or property damage, health issues or otherwise that may befall the Client as a result of using any Vendor service.`,
    miscellaneousProvisionsTitle: "16. Miscellaneous Provisions:",
    miscellaneousProvisions: `16-1 Governing Law: This Agreement between the Client and Leago and any access to or use by the Client of the Platform or Service is subject to the laws and regulations of the Kingdom of Saudi Arabia. Any dispute that may arise between the Client and Leago regarding the implementation or interpretation of this Agreement shall be settled amicably, and if this is not possible, the courts of Jeddah shall be the competent authority to settle it.
16-2 Severability: If any part of this Agreement is deemed invalid or unenforceable, that part of the Agreement will be construed to reflect the original intent of the parties. The remaining parts will remain in full force and effect. No failure on Leago's part to enforce any provision of this Agreement will be deemed a waiver of our right to enforce that provision. Our rights under this Agreement will survive any termination of this Agreement.
16-3 Assignment: Leago may assign or delegate its rights or obligations under these Terms and Conditions and/or Leago's Privacy Policy, in whole or in part, to any person or entity at any time with or without your consent. You may not assign or delegate any of your rights or obligations under the Terms and Conditions or Privacy Policy without obtaining prior written consent from Leago, and any unauthorized assignment and delegation by you is null and void.
16-4 Notices to Clients: Leago may send to Clients reports, statements, notices, and any other correspondence via the email address they specify in their accounts. All correspondence and notices shall be deemed duly issued and sent to the Client when sent electronically by Leago to the Client at the email address specified in the Client's account.
16-5 Leago Notices: The Client may send reports, statements, notices, and any other correspondence to Leago at the company's email info@leago.org and all correspondence and notices are deemed received or provided (as applicable) to Leago when received electronically by Leago at info@leago.org
16-6 Headings: The headings and captions contained in this Agreement are mentioned for convenience only but do not in any way define or describe the scope or content of any provision of this Agreement.
16-7 Neutral Address: Where used in this document and as required by context, the singular shall include the plural, the plural shall include the singular, the use of any gender shall include both genders, and the words "hereof," "herein," and "hereafter" refer to the entire Agreement and not to any text or section.
You acknowledge that you have read, understood, and agreed to be bound by these Terms and Conditions.`,
  },
  ar: {
    title: "الشروط و الأحكام",
    mainTitle: " الشروط و الأحكام الخاصة بالشركة :",
    discription:
      "تنظم هذه الشروط والأحكام العلاقة بينك و/أو شركتك وشركة ليقو السعودية لتقنية المعلومات، وهي شركة مرخصة من قبل وزارة التجارة السعودية، وتغطي استخدامك ووصولك إلى المنصة و/أو التطبيق. ومن خلال الوصول إلى المنصة و/أو التطبيق واستخدامهما، فإنك تقر بأنك قد قرأت وفهمت ووافقت على الالتزام بهذه الشروط والأحكام، وحسبما يتم تعديلها من وقت لآخر. إذا كنت لا توافق على هذه الشروط والأحكام، فيجب عليك التوقف عن استخدام أو الوصول إلى المنصة و/أو التطبيق على الفور. إذا كنت تستخدم المنصة نيابة عن الغير بما في ذلك، على سبيل المثال لا الحصر، كيان تجاري، فأنت تضمن أنك مصرح لك وتتمتع بالسلطة لإلزام هذا الغير بهذه الشروط والأحكام.",
    difinitionsTitle: "1. التعريفات :",
    difinitions: `أ‌-	تُستخدم المصطلحات التالية في سياق هذه الشروط والأحكام ولها معاني محددة.
ب‌-	"الحساب" يعني الحساب المطلوب من المستخدمين تسجيله من خلال التطبيق و/أو المنصة لاستخدام الخدمات بما في ذلك الوثائق المطلوبة لإكمال تسجيل الحساب.
ت‌-	"الرسوم الإضافية" تعني الرسوم التي قد يتكبدها العميل نتيجة لاستخدام العميل لسيارة، بما في ذلك، على سبيل المثال لا الحصر، مخالفات المرور ووقوف السيارات ورسوم العبور ورسوم الوقود ورسوم الأميال الزائدة وقسط التأمين ورسوم عقوبة الإنهاء المبكر (كما هو موضح في البند 8).
ث‌-	يُقصد بمصطلح "الاتفاقية" و "الشروط والأحكام" بشكل جماعي جميع الأحكام والشروط والإخطارات الواردة أو المشار إليها في هذه الوثيقة (حسبما يتم تعديلها من وقت لآخر) وجميع قواعد شركة ليقو الأخرى والسياسات المتاحة على المنصة (بما في ذلك على سبيل المثال لا الحصر، سياسة الخصوصية والتوجيهات والإجراءات التي قد يتم نشرها من وقت لآخر على المنصة).
ج‌-	"التطبيق" يعني تطبيق الهاتف المتحرك الذي تقدمه شركة ليقو والذي يربط العملاء بالبائعين لاستئجار السيارات.
ح‌-	يُقصد بمصطلح "العميل" و "أنت" و "الخاص بك" بشكل جماعي شخصًا أو شركةً تتواصل و/أو تشترك و/أو ترغب في استئجار سيارة أو سيارات من بائع من خلال المنصة و/أو التطبيق.
خ‌-	"أمر التأكيد" يعني أي وجميع أوامر التأكيد المكتوبة أو المنقولة إلكترونيًا والتي ترسلها شركة ليقو لاستئجار سيارة والتي قد تشمل، بما في ذلك على سبيل المثال لا الحصر، رقم الحجز، ووصف السيارة، وموقع وتاريخ ووقت الاستلام، وموقع وتاريخ ووقت التسليم وتفاصيل البائع وشروط الدفع والكمية ومدة استئجار السيارة وأي شرط خاص.
د‌-	"الحجز المؤكد" يعني تأكيد الحجز من قبل البائع بعد استلام طلب حجز استئجار السيارة المقدم من العميل من خلال المنصة.
ذ‌-	"المحتوى" يعني أي محتوى يتم تقديمه أو إنشاؤه أو طرحه أو عرضه من خلال المنصة أو التطبيق (بما في ذلك على سبيل المثال لا الحصر، أي ملف تعريفي للسيارة وأي نص ومراسلات وصور ورسومات وبرامج وتطبيقات وتسجيلات فيديو وتسجيلات صوتية وأصوات وتصميمات ومزايا ومواد أخرى متوفرة على المنصة). يتضمن المحتوى، على سبيل المثال لا الحصر، محتوى المستخدم الذي قد يقدمه المستخدم.
ر‌-	"خطاب التفويض بتسجيل التصنيف الائتماني" يعني خطاب التفويض بتسجيل التصنيف الائتماني الذي توقعه لتفويض شركة ليقو لتحصيل الرصيد الائتماني الخاص بك في النموذج المرفق بهذه الوثيقة في الملحق 1.
ز‌-	"المحفظة الرقمية" تعني أي رصيد يتم الاحتفاظ به على المنصة و/أو التطبيق بواسطة شركة ليقو ويتم ربطه بحساب المستخدم والذي يمكن من خلاله تسجيل أي أرصدة مستحقة للمستخدم، وفقًا لأحكام البند 5.
س‌-	"مبلغ الخصم" يعني مبلغ أو قيمة الخصم المطبق على دفعة الإيجار كما هو موضح في أمر التأكيد و/أو الفاتورة.
ش‌-	"رسوم عقوبة الإنهاء المبكر" تعني رسوم العقوبة المستحقة الدفع من قبل العميل في حالة الإنهاء المبكر لاتفاقية استئجار السيارة من قبل العميل (على النحو المنصوص عليه في البند 8-1 (8)).
ص‌-	"دفعة الإيجار" تعني مبلغ الإيجار للسيارة كما هو موضح في أمر التأكيد و/أو اتفاقية استئجار السيارة ويتم احتسابها على العملاء من خلال المنصة.
ض‌-	"رسوم الإرجاع في منتصف الشهر" تعني رسوم ثابتة مستحقة الدفع من قبل العميل في حالة الإرجاع المبكر للسيارة (كما هو موضح في البند 9-6)، والتي قد تحددها شركة ليقو من وقت لآخر ويتم الإخطار بها على المنصة و/أو التطبيق.
ط‌-	"المنصة" تعني أي أداة متاحة عبر الإنترنت يتم توفيرها و/أو معالجتها و/أو صيانتها بواسطة شركة ليقو (بما في ذلك على سبيل المثال لا الحصر، من خلال تطبيق شركة ليقو والموقع الإلكتروني وجميع الصفحات الفرعية والنطاقات الفرعية وجميع المحتويات والخدمات والمنتجات المتاحة على أو عبر المنصة الموجودة على: https://www.legao.org أو أي نطاق آخر ذي صلة يتيح الوصول إلى الخدمات أو تسهيل تقديمها)
ظ‌-	تعني "سياسة الخصوصية" ممارسات الخصوصية لشركة ليقو فيما يتعلق باستخدام محتوى المستخدم والمنصة والخدمات المتاحة على: https://www.legao.org.
ع‌-	"الخدمة" تعني الخدمات المتاحة عبر الإنترنت و/أو دون الاتصال بالإنترنت، والتي تقدمها شركة ليقو لتوفير واستخدام التكنولوجيا التي طورتها شركة ليقو من أجل التعاون والاتصال والدفع بين البائعين والعملاء، بما في ذلك على سبيل المثال لا الحصر، الوصول إلى تطبيق شركة ليقو ، والمجتمع الإلكتروني عبر الإنترنت، وأدوات الاتصال، وخدمات الدفع.
غ‌-	"الاستئجار الناجح" يعني قبول العميل لأمر تأكيد كما يتضح من إيداع أو دفع كل أو جزء من دفعة الإيجار.
ف‌-	"محتوى الغير" يعني أي محتوى ينتمي إلى أو ينشأ من الغير.
ق‌-	"محتوى المستخدم" يعني أي محتوى، مكتوب أو غير ذلك، تم إنشاؤه أو تقديمه أو صياغته أو طرحه أو عرضه من خلال المنصة (بما في ذلك على سبيل المثال لا الحصر، أي نص ومراسلات وصور) من قبل المستخدمين أثناء استخدام المنصة.
ك‌-	"المستخدم" يعني الشخص أو الشركة أو المؤسسة التي قامت بزيارة أو استخدام المنصة و/أو الخدمة. قد يكون المستخدم عميلاً أو بائعاً أو كليهما أو ليس أيًا منهما.
ل‌-	"اتفاقية استئجار السيارة" تعني الاتفاقية التي سيتم إبرامها بين البائع والعميل لإضفاء الطابع الرسمي على الترتيبات المنفذة بينهما والتي تحدد بدورها الشروط الرئيسية للمعاملة التي تتم بينهما (بما في ذلك على سبيل المثال لا الحصر، وصف ومدة استئجار السيارة، ودفعة الإيجار وشروط الدفع).
م‌-	"استئجار السيارة" يعني استئجار العميل لسيارة من بائع باستخدام المنصة.
ن‌-	"السيارة" تعني سيارة البائع المسجّلة في المنصة والتي قد استأجرها عميل أو وافق البائع على استئجارها للعميل من خلال المنصة، والتي تشمل أجزاءها ومكوناتها وملحقاتها ووثائق :التسجيل الخاصة بها.
ه‌-	"البائع" شركة تأجير سيارات او مؤسسة تقدم خدمات البائع للعميل عن طريق المنصة.
و‌-	"خدمات البائع" تعني أي خدمات يقدمها البائعون فيما يتعلق باستئجار سيارة كما هو محدد في اتفاقية استئجار السيارة، بما في ذلك على سبيل المثال لا الحصر، توفير سيارات تعمل جيدًا دون أي أضرار، والإبلاغ عن أي رسوم إضافية، وتوفير المساعدة في حالة تعطل السيارة.
`,
    aboutUsTitle: "2. لمحة حول شركة ليقو :",
    aboutUs: `شركة ليقو عبارة عن منصة تربط بين البائعين والعملاء. توفر شركة ليقو إمكانية الوصول إلى المجتمع الافتراضي للبائعين الخاص بشركة ليقو وسهولة التعاون من خلال أدوات الاتصال لشركة ليقو وأدوات الدفع الآمنة.
 2-1 إنك تفهم وتوافق على أن البائعين ليسوا موظفين أو وكلاء لـدى شركة ليقو وأن أي معاملة و/أو اتفاقية (مثل اتفاقية استئجار السيارة) يتم إبرامها نتيجة لاستخدامك للخدمات، سواء أكانت شفهية أو مكتوبة، بينك وبين البائع فقط، ولا تعتبر شركة ليقو طرفًا فيه. تتمتع أنت والبائع بسلطة تقديرية كاملة فيما يتعلق بشروط أي اتفاقية استئجار سيارة. بصرف النظر عن هذه الشروط والأحكام، سيُطلب منك، في وقت استلام السيارة أو في وقت قريب من ذلك، إبرام اتفاقية استئجار السيارة والتي تشكل علاقة تعاقدية مباشرة بين العميل والبائع. أنت تقر وتوافق على أنه في هذه الحالة، لن تكون شركة ليقو طرفًا في اتفاقية استئجار السيارة ولن تكون مسؤولة عن تنفيذ التزامات أي اتفاقية استئجار سيارة مبرمة بينك وبين أي بائع، وتُخلي شركة ليقو مسؤوليتها من أي التزامات ناشئة عن أو تتعلق بأي اتفاقية استئجار سيارة.
 2-2 إنك توافق وتقر بأن شركة ليقو لا تمتلك أو تبيع أو تستأجر أو تُعيد استئجار أو تؤجر أي سيارة وأن البائعين هم المسؤولون الوحيدون عن استئجار السيارة وأن شركة ليقو تعمل كوسيط بين العملاء والبائعين ويتمثل دورها فقط في تسهيل توافر الخدمات للعملاء والبائعين.
 2-3 لا تُصادق شركة ليقو على أي بائع على بائع آخر لخدمة العميل. بينما تبذل شركة ليقو جهودًا معقولة تجاريًا لتأكيد أن البائعين مرخصون ولديهم الموافقات الحكومية المطلوبة لتوفير خدمة استئجار سيارة، فإننا لا نقدم أي تعهد أو ضمان أو إقرار فيما يتعلق بالترخيص أو القدرة أو الكفاءة أو الامتثال أو الجودة أو المؤهلات الخاصة بأي بائع. إنك توافق على وتفهم أنه من واجبك الاستفسار عن ترخيص أي بائع أو قدرته أو كفاءته أو امتثاله أو جودته أو مؤهلاته وتقييم كل ذلك.
 2-4 بالرغم من أن شركة ليقو تتطلب من البائعين تقديم معلومات دقيقة، إلا أننا لا نؤكد على أي هوية مزعومة لأي بائع. يوافق العملاء على البحث عن أي بائع وتقييمه بشكل مستقل.
2-5 بالرغم من أن شركة ليقو تتطلب من البائعين امتلاك تأمين تجاري و/أو تأمين المسؤولية المهنية، فإن شركة ليقو لا تتعهد أو تضمن حصول البائعين على أي تأمين تجاري و/أو تأمين المسؤولية المهنية، ولا تقدم شركة ليقو أي تعهد أو ضمان فيما يتعلق بكفاية هذا التأمين التجاري و/أو تأمين المسؤولية المهنية.
 2-6 إنك تفهم وتقر بأن سعر استئجار سيارة المقدم لك يعتمد على تصنيفك الائتماني كما هو متاح لدى الشركة السعودية للمعلومات الائتمانية (سمة). من خلال قبول الأحكام والشروط الخاصة بنا، فإنك تفوضنا للحصول على تصنيفك الائتماني من الشركة السعودية للمعلومات الائتمانية (سمة). كما أنك تخوّلنا بالإفصاح عن معلوماتك للشركة السعودية للمعلومات الائتمانية (سمة).
`,
    amendmentsTermsAndConditionsTitle:
      "3. التغييرات المنفذة على الشروط و الأحكام :",
    amendmentsTermsAndConditions: ` 3-1 إنك توافق على أنه يجوز لشركة ليقو تعديل هذه الاتفاقية من وقت لآخر، ووفقًا للتقدير المطلق لشركة ليقو وحدها. بالرغم من أننا سنبذل قصارى جهدنا لإعلامك بأي تعديل يتم على هذه الاتفاقية، إلا أننا لن نكون مطالبين بتزويدك بإخطار مسبق بهذه التعديلات أو التغييرات على هذه الاتفاقية وسوف يشكل استخدامك المستمر للمنصة أو الخدمات موافقتك على هذه التعديلات أو التغييرات المنفذة على الاتفاقية.
3-2  عند إجراء أي تعديل أو تغيير على هذه الاتفاقية، سننشر الاتفاقية المعدلة على الرابط المخصص المتاح على منصتنا. استخدامك المستمر للمنصة و/أو الخدمة بعد تاريخ نشر نسخة منقحة من هذه الاتفاقية يشكل موافقتك على شروطها.
3-3  إنك توافق وتتعهد بمراجعة الشروط والأحكام الخاصة بنا في كل مرة تزور فيها منصتنا و/أو قبل استخدامك لأي من الخدمات. إذا كنت لا توافق على الشروط والأحكام الخاصة بنا، حسبما يتم تحديثها من وقت لآخر، فإنك تتعهد بالتوقف عن استخدام منصتنا و/أو خدماتنا على الفور.
`,
    registerAndClientResponsibilitiesTitle:
      "4. تسجيل الحساب و مسؤوليات العميل :",
    registerAndClientResponsibilities: ` 4-1 إذا كنت ترغب في استخدام خدماتنا، فيجب عليك إنشاء حساب شخصي بحيث يتضمن اسم مستخدم مميز وكلمة مرور للوصول إلى الخدمة. وكل عميل مسؤول عن الحفاظ على أمن حسابه وجميع الأنشطة التي تُجرى بموجب الحساب وأي إجراءات أخرى يتم اتخاذها فيما يتعلق بالحساب. وإنك تتعهد بتقديم معلومات دقيقة وكاملة والحفاظ على معلومات حسابك وتحديث حسابك والحفاظ على سريته. كما إنك توافق على إخطار شركة ليقو فورًا بأي استخدام غير مصرح به للحساب، أو أي انتهاكات أخرى للأمن. ولن نكون مسؤولين عن أي التزامات أو خسائر أو أضرار ناشئة عن الاستخدام غير المصرح به لجهاز الكمبيوتر أو الهاتف المتحرك الخاص بك أو أي جهاز كمبيوتر آخر و/أو الحساب.
 4-2 نحتفظ بالحق في تعليق حسابك أو إنهائه في أي وقت، بما في ذلك ما إذا ثبت أن أي محتوى مستخدم أو معلومات مقدمة أثناء عملية التسجيل أو بعد ذلك غير دقيقة أو خاطئة أو مضللة أو استعادة أي اسم مستخدم تقوم بإنشائه من خلال الخدمات التي تنتهك هذه الاتفاقية.
 4-3 عند استخدام الخدمات، يتعهد العملاء بتزويد شركة ليقو بمعلوماتهم الشخصية (بما في ذلك الاسم والعنوان وعنوان البريد الإلكتروني وتاريخ الميلاد وبيانات رخصة القيادة ومعلومات البطاقة الائتمانية ورقم الهاتف). وإنك توافق وتقبل بأن شركة ليقو ستشارك أيًا من هذه المعلومات مع البائعين المتاحين الذين قد يكونون قادرين على تقديم خدمات البائعين.
 4-4 عند تنفيذ الاستئجار الناجح، فيوافق العملاء على أنه سيتم تمديد أو تعديل استئجار السيارة من خلال المنصة فقط، وأن أي دفعات أخرى أو متكررة مقابل استئجار السيارة لن تُسدد إلا من خلال المنصة.
`,
    digitalWalletTitle: "5. المحفظة الرقمية :",
    digitalWallet: ` 5-1 تحتفظ شركة ليقو ، لكل حساب مستخدم، بمحفظة رقمية يتم فيها الاحتفاظ بأي رصيد ائتماني وفقًا لشروط هذه الاتفاقية.
5-2  سيتم تخزين أي رصيد ائتماني في المحفظة الرقمية لمدة 60 يومًا قبل انتهاء صلاحيته، ويمكن للمستخدم استخدامه للدفع مقابل أي خدمة تقدمها شركة ليقو من خلال المنصة و/أو التطبيق.
 5-3 لتجنب الشك، لا يمكن للمستخدمين إيداع أموال أو رصيد ائتماني في المحفظة الرقمية. لا يمكن استخدام المحفظة الرقمية إلا لتسجيل وتخزين أي رصيد ائتماني صادر عن شركة ليقو إلى المستخدم وفقًا لشروط هذه الاتفاقية.
`,
    userBehaviorRestrictionsTitle: "6. القيود المفروضة على سلوك المستخدم :",
    userBehaviorRestrictions: ` 6-1 إنك توافق على أنك لن تقوم، تحت أي ظرف من الظروف، بنقل أي محتوى: (1) غير قانوني أو يشجع على نشاط غير قانوني؛ أو (2) يعمل على التشهير أو المضايقة أو الإساءة أو التهديد أو التحريض على العنف تجاه أي فرد أو مجموعة؛ أو (3) سياسي أو إباحي أو تمييزي أو يسهم بأي شكل آخر في إيذاء أو ترويع أي فرد أو مجموعة على أساس الدين أو الجنس أو الميول الجنسية أو العرق أو الأصل العرقي أو السن أو الإعاقة؛ أو (4) يمثل رسالة بريد إلكتروني ضارة وغير مرغوب فيها، ويشكل إعلانًا غير مصرح به أو غير مرغوب فيه، أو أي شكل آخر من أشكال الطلب غير المصرح به؛ أو (5) يحتوي على أو يثبت أي فيروسات أو فيروسات متنقلة أو برامج ضارة أو أحصنة طروادة أو أي محتوى آخر مصمم أو مخصص لتعطيل أو إتلاف أو تقييد عمل أي برامج أو أجهزة أو معدات اتصال أو إتلاف أو الحصول على وصول غير مصرح به إلى أي بيانات أو معلومات أخرى خاص بأي من الغير؛ أو (6) ينتهك أي حق ملكية لأي طرف، بما في ذلك براءات الاختراع أو العلامات التجارية أو الأسرار التجارية أو حقوق النشر أو حق الدعاية أو الحقوق الأخرى؛ أو (7) ينتحل هوية أي شخص أو كيان، بما في ذلك أي من موظفينا أو ممثلينا؛ أو (8) ينتهك خصوصية أي من الغير.
6-2  من خلال الوصول إلى أو استخدام المنصة و/أو الخدمات، فإنك تقر وتضمن ما يلي: (1) لديك رخصة قيادة سارية في المملكة العربية السعودية؛ و(2) لديك السلطة لإبرام و/أو الالتزام بهذه الاتفاقية بشكل صحيح؛ و(3) يتم استخدامك للخدمات للأغراض القانونية فقط التي تسمح بها هذه الاتفاقية؛ و(4) يتوافق استخدامك للخدمات مع جميع القوانين والقواعد واللوائح في المملكة العربية السعودية، ومع جميع سياسات شركة ليقو ؛ وحسبما يتم تعديلها من وقت لآخر.
 6-3 إنك تقر وتضمن بأن عمرك يزيد عن 18 عامًا. لا تستهدف شركة ليقو أي محتوى للأطفال أو المراهقين تحت سن 18 عامًا، ولا نسمح لأي عملاء دون سن 18 عامًا باستخدام خدمتنا. يُرجى التوقف فورًا عن استخدام المنصة إذا كنت دون هذا السن القانوني.
6-4  وفقًا لتقديرنا، يجوز لنا، أو التكنولوجيا التي نستخدمها، مراقبة و/أو تسجيل تفاعلاتك العامة مع الخدمة. ومع ذلك، فإن أي مسؤولية أو خسارة أو ضرر يحدث نتيجة لأي تفاعلات للمستخدم هو مسؤوليتك وحدك، كما هو موضح بشكل إضافي في البندين 14 و15 من هذه الاتفاقية.
 6-5 يحق لنا، وفقًا لتقديرنا الخاص، أن نحدد ما إذا كان سلوك العميل مناسبًا أم لا ويتوافق مع هذه الشروط والأحكام أم لا. ولدينا أيضًا الحق في إنهاء أو رفض الوصول إلى أي حساب وخدمة لأي عميل لأي سبب، سواء بموجب إخطار مسبق أو بدونه.
`,
    userContentTitle: "7. محتوى المستخدم :",
    userContent: ` 7-1 لسنا مسؤولين عن أي عرض عام أو إساءة استخدام لمحتوى المستخدم الخاص بك. يتحمل المستخدمون وحدهم المسؤولية عن المحتوى وأي ضرر ناتج عن أي محتوى مستخدم يقدمونه أو ينشرونه أو يحمّلونه أو يربطونه أو يوفرونه أثناء استخدام الخدمة. كما إنك تقر بأن أي مسؤولية أو خسارة أو ضرر يحدث نتيجة لأي محتوى مستخدم من هذا القبيل يخضع لمسؤوليتك وحدك. كما تتعهد وتوافق على تعويضنا وإبراء ذمتنا (وأي من الغير) من أي مسؤولية أو خسارة أو ضرر قد يقع نتيجة لأي محتوى مستخدم.
7-2  من وقت لآخر، يمكن للعملاء تقديم تعقيبات عن البائعين؛ ولا تشكل هذه التعقيبات ضمانًا أو تعهدًا أو توقعًا فيما يتعلق بنتائج أي خدمة بائع في المستقبل. ولن تكون شركة ليقو ملزمة بعرض هذه التعقيبات ويجوز لها إزالة هذه التصنيفات في أي وقت وفقًا لتقديرها الخاص. لن تتحمل شركة ليقو أي مسؤولية أو التزام من أي نوع عن أي تعقيب تواجهه في أو من خلال المنصة، ويخضع أي استخدام أو اعتماد على هذه التعقيبات لمسؤوليتك الخاصة.
7-3  يتم توفير محتوى المستخدم المنشور على المنصة، مثل مشاركات المدونة أو التعقيبات، لأغراض إعلامية فقط، دون أي ضمان بأن هذا المحتوى سليم أو صحيح أو دقيق.
7-4  يقر المستخدمون ويضمنون أن لديهم الحق في نشر جميع محتويات المستخدم التي يقدمونها. على وجه التحديد، يضمن المستخدمون أنهم قد امتثلوا تمامًا لأي تراخيص للغير تتعلق بمحتوى المستخدم (إن أمكن)، واتخذوا جميع الخطوات اللازمة لنقل أي شروط مطلوبة إلى المستخدمين النهائيين.
 7-5 يوافق المستخدمون ويقرون بأن شركة ليقو لها الحق، وفقًا لتقديرها الخاص، في عرض ومراقبة أي محتوى مستخدم، وتحديد ما إذا كان أي محتوى مستخدم ملائمًا أم لا يتوافق مع هذه الشروط والأحكام، أو رفض أو إزالة أي محتوى مستخدم، حسب الرأي المعقول لشركة ليقو ، ينتهك أي سياسة لشركة ليقو أو يعتبر - بأي شكل - ضارًا أو غير لائق أو غير مرغوب فيه. كما يوافق المستخدمون أيضًا على أن شركة ليقو لها الحق في تنفيذ عمليات التنسيق والتحرير وإجراء التغييرات الأخرى على محتوى المستخدم أو الطريقة التي يتم بها عرض أي محتوى مستخدم على المنصة.
 7-6 باستثناء المحتوى الذي ينشأ من شركة ليقو ، لا ندعي ملكية أي محتوى تنشره أو تحمّله أو تربطه. كما إنك تحتفظ بكامل ملكية محتوى المستخدم الذي تنشره وتتحكم فيه وتتحمل المسؤولية عنه. من خلال نشر أي محتوى بما في ذلك على سبيل المثال لا الحصر، صور وشعارات الشركة والتعقيبات عبر المنصة، فإنك تمنح صراحةً شركة ليقو وخلفاءنا ترخيصًا عالميًا قابلاً للترخيص من الباطن ومدفوعًا بالكامل وخاليًا من الأتعاب وغير حصري لاستخدام المحتوى وإعادة إصداره وعرضه وتعديله وتهيئته وتوزيعه وتنفيذه فيما يتعلق بالغرض التجاري لشركة ليقو. لا يمنح هذا الترخيص شركة ليقو الحق في بيع محتوى المستخدم أو توزيعه خارج منصتنا.
`,
    addtionalFeesAndRentalPaymentTitle: "8. الرسوم الاضافية و دفعة الإيجار :",
    addtionalFeesAndRentalPayment: `8-1  يوافق العميل ويقبل بأنه يتم حساب الرسوم الإضافية على النحو التالي:
 (1) بالنسبة لغرامة المرور و/أو وقوف السيارات، يتم تطبيق رسوم إدارية بنسبة 16%. وعلى هذا النحو، يتعهد العميل بدفع غرامات المرور و/أو غرامات وقوف السيارات المطبقة ومبلغ يعادل 16% من غرامات المرور و/أو غرامات وقوف السيارات كرسوم إدارية.
(2)  بالنسبة لرسوم الوقود، يتم تطبيق رسوم إدارية بنسبة 20%. على هذا النحو، يتعهد العميل بدفع رسوم الوقود المطبقة ومبلغ يعادل 20 % من رسوم الوقود كرسوم إدارية.
 (4) بالنسبة لأية أميال زائدة، يتم تطبيق رسوم إدارية قدرها 45 هللة لكل كيلومتر. على هذا النحو، يتعهد العميل بدفع 45 هللة لكل كيلومتر كرسوم إدارية إذا تجاوز إجمالي الكيلومترات المقطوعة الحد المسموح حسب العقد في كل شهر.
 (5) يتم احتساب قسط التأمين حسب السيارة.
(6)  يجب دفع أي رسوم إضافية يتم تكبدها بموجب هذا البند 8-1 على الفور، بعد إخطار شركة ليقو للعميل بالتكاليف الإضافية التي تم تكبدها.
(7) في حالة تخلف العميل عن الوفاء بالتزاماته بالدفع بموجب هذه الاتفاقية و/أو اتفاقية استئجار السيارة و/أو أخفق في الاستجابة لإخطارات شركة ليقو بخصوص أي دفعة متأخرة، فسوف يتم استرداد السيارة من قبل البائع مع احتساب جميع الرسوم المطبقة والرسوم المفروضة على العميل. سيقوم البائع بالتواصل مع العميل فيما يتعلق بعملية استرداد السيارة، ويتعاون العميل مع البائع وفقًا لذلك. وسيستمر العميل في تحمل أي رسوم مطبقة بموجب هذه الاتفاقية و/أو اتفاقية استئجار السيارة حتى تُعاد السيارة بنجاح إلى البائع. وفي حالة عدم تعاون العميل و/أو تسليم السيارة للبائع في الوقت المحدد، فيحق للبائع وشركة ليقو تعطيل و/أو تتبع السيارة و/أو إشراك الغير أو السلطات المختصة حسبما قد يكون ملائمًا (مثل الشرطة). إذا تم استرداد سيارة بموجب هذا البند 8-1- (7) (قبل انقضاء مدة اتفاقية استئجار السيارة)، فإن أي أيام غير مستخدمة دفع العميل قيمتها بالفعل ستُضاف إلى المحفظة الرقمية الخاصة بالعميل على أساس تناسبي لتعويض أي مبلغ مستحق إلى العميل. إذا كان هناك أي مبلغ مستحق السداد مملوك من قبل العميل لصالح شركة ليقو و/أو البائع، فتستمر مسؤولية العميل عن دفع هذا المبلغ المستحق السداد في السريان. وتحتفظ شركة ليقو بالحق في استرداد السيارة. وسيتم تصنيف أي أيام غير مستخدمة على أنها رصيد دائن يُضاف للعميل لتعويض أي مبلغ مستحق. وسيظل أي مبلغ متبقٍ خاضعًا للدفع من قبل العميل.
 (8) في حالة الإنهاء المبكر من قبل العميل لاتفاقية استئجار السيارة، فيوافق العميل على احتساب رسوم عقوبة الإنهاء المبكر، بالإضافة إلى رسوم إدارية مطبقة لمرة واحدة بقيمة 70 ريال سعودي. يوافق العميل ويقر كذلك بأنه سيتم حساب رسوم عقوبة الإنهاء المبكر على النحو التالي:
1.	في حالة الإنهاء المبكر من قبل العميل لاتفاقية استئجار السيارة المبرمة لمدة تزيد عن 30 يومًا، فيكون مبلغ رسوم عقوبة الإنهاء المبكر معادلاً لمبلغ الخصم المطبق مضروبًا في عدد الأشهر (أو جزء منها) التي كانت خلالها السيارة في حوزة العميل.
2.	في حالة الإنهاء المبكر من قبل العميل لاتفاقية استئجار السيارة المبرمة لمدة تصل إلى 30 يومًا، فيوافق العميل على أنه لا يحق للعميل استرداد أي مبالغ وتعتبر دفعة الإيجار المقابلة للأيام المتبقية لاستئجار السيارة مستحقة وواجبة السداد كرسوم عقوبة الإنهاء المبكر.
 8-2 يفهم العملاء ويقرون بأن الرسوم الإضافية تخضع للتغيير من وقت لآخر ويمكن توضيحها في أمر التأكيد على وجه التحديد. إذا كان هناك أي تضارب أو تعارض بين الرسوم الإضافية المنصوص عليها في البند 8-1 أعلاه والرسوم الإضافية المنصوص عليها في أمر التأكيد، فسوف تكون الغلبة للرسوم الإضافية المنصوص عليها في أمر التأكيد.
8-3  يجب على العملاء سداد دفعة الإيجار إلى شركة ليقو بصورة شهرية، على النحو المحدد في أمر التأكيد و/أو اتفاقية استئجار السيارة.
8-4  يوافق العملاء على أنهم سيسددون دفعة الإيجار والرسوم الإضافية (إن وجدت) من خلال المنصة أو التطبيق فقط، بما في ذلك الدفعات المتكررة بالإضافة إلى المعاملات اللاحقة التي لا تتعلق بالضرورة بالاستئجار الأولي للسيارة.
8-5  يتحمل العملاء المسؤولية عن الضرائب (ضريبة القيمة المضافة) حسب الاقتضاء، وأي رسوم معالجة مرتبطة باستخدامهم للخدمات واستئجار السيارة، وأي رسوم خاصة بالبطاقة الائتمانية ورسوم المعاملات المصرفية (إن وجدت).
8-6  تقبل شركة ليقو الدفعات عن طريق البطاقة الائتمانية وبطاقة الخصم المباشر، بما في ذلك على سبيل المثال لا الحصر، بطاقة فيزا وماستر كارد. ويمكن للعملاء سداد الدفعات بالعملة المدرجة في أمر التأكيد الذي يتلقونه. يصرح العملاء -بموجب هذه الوثيقة- لشركة ليقو بفرض رسوم على بطاقتهم الائتمانية مقابل أي دفعة إيجار ورسوم إضافية (إن وجدت)، بالإضافة إلى أي دفعات أو مبالغ أخرى متكررة مستحقة كجزء من خدماتنا. من خلال قبول الشروط والأحكام الخاصة بنا، يوافق العملاء على أنهم يصرحون لشركة ليقو بتحصيل الرسوم منهم تلقائيًا مقابل أي دفعة إيجار ورسوم إضافية (إن وجدت)، بالإضافة إلى أي دفعات أو مبالغ أخرى متكررة (حسب الاقتضاء)، دون الحاجة إلى أي إخطار أو موافقة إضافية. ويعتبر العملاء مسؤولين عن توفير معلومات كاملة ودقيقة عن الفواتير لشركة ليقو وإخطار شركة ليقو بأي تغييرات تطرأ على هذه المعلومات.
 8-7 تخضع جميع الدفعات المسددة عبر الإنترنت أيضًا لأحكام وشروط مزود خدمة التاجر المعني. كما يرجى مراجعة شروط وأحكام مزود خدمة التاجر وسياسة الخصوصية قبل الدخول في أي معاملة. ويجب عليك الاحتفاظ بنسخة من سجلات المعاملات.
 8-8 لن تتعامل شركة ليقو مع أو تقدم أي خدمات للبلدان الخاضعة لمكتب مراقبة الأصول الأجنبية والبلدان الخاضعة للعقوبات.
 8-9 سوف تزودك شركة ليقو مباشرة أو من خلال مزود خدمة التاجر الخاص بها، بتأكيد الدفع الإلكتروني فورًا بعد إتمام الدفع بنجاح من خلال المنصة. كما ستزودك شركة ليقو أيضًا بفاتورة صادرة عن البائع للاطلاع عليها وكمرجع لك فيما يتعلق بدفعة الإيجار والرسوم الإضافية (إن وجدت) عند تلقي أي من هذه الدفعات.
`,
    cancellationOfConfirmedBookingAndEarlyReturnsTitle:
      "9. الغاء الحجز المؤكد و المرتجعات المبكرة :",
    cancellationOfConfirmedBookingAndEarlyReturns: `إلغاء الحجوزات المؤكدة :
9-1  يوافق العملاء ويقبلون على أن الحجز المؤكد سيكون ساريًا لمدة 24 ساعة بدءًا من تأكيد البائع، وبعد ذلك سيتم إلغاؤه تلقائيًا.
9-2  يجب على العملاء إبلاغ شركة ليقو مباشرة بجميع عمليات إلغاء الحجوزات المؤكدة. إذا تم إلغاء الحجز المؤكد من قبل العميل مع تقديم إخطار مسبق قبل 12 ساعة على الأقل من تسليم السيارة، فيجب تنفيذ الإلغاء بدون عقوبة وسيتم رد دفعة الإيجار (أو جزء منها) التي تم استلامها من قبل شركة ليقو إلى المحفظة الرقمية للعميل، مع مراعاة أي تكاليف ذات صلة، بما في ذلك، على سبيل المثال لا الحصر، أي رسوم تحويل مصرفي أو رسوم البطاقة الائتمانية.
 9-3 إذا تم إلغاء الحجز المؤكد من قبل العميل قبل أقل من 12 ساعة من تسليم السيارة، فسيتم احتساب مبلغ يعادل 25% من دفعة الإيجار على العميل وسيتم رد المبلغ المتبقي (مع مراعاة أي تكاليف ذات صلة، بما في ذلك، على سبيل المثال لا الحصر، أي رسوم تحويل مصرفي أو رسوم البطاقة الائتمانية) إلى المحفظة الرقمية للعميل.
 9-4 إذا قام العميل، في غضون 7 أيام من تاريخ التسليم المتفق عليه، بإخطار شركة ليقو بعدم قدرته على استلام السيارة، فسيتم احتساب مبلغ يعادل 50% فقط من دفعة الإيجار على العميل وسيتم رد المبلغ المتبقي (مع مراعاة أي تكاليف ذات صلة، بما في ذلك، على سبيل المثال لا الحصر، أي رسوم للتحويل المصرفي أو رسوم البطاقة الائتمانية) إلى المحفظة الرقمية للعميل.
9-5  إذا قام العميل، بعد 7 أيام من تاريخ التسليم المتفق عليه، بإخطار شركة ليقو أو تخلف عن إبلاغها بعدم قدرته على استلام السيارة، فسيتم احتساب كامل دفعة الإيجار على العميل ولن يحق له استرداد أي مبلغ.
المرتجعات المبكرة :
 9-6 يجوز للعميل إرجاع سيارة قبل انقضاء مدة اتفاقية استئجار السيارة. ستعتمد الرسوم المطبقة للقيام بذلك على ما إذا كان العميل يرغب في إعادة السيارة في أو قبل أو بعد تاريخ استحقاق الدفعة الشهرية التالية كما هو محدد في أمر التأكيد و/أو اتفاقية استئجار السيارة، وما إذا كانت أي رسوم لعقوبة الإنهاء المبكر مطبقة كما هو محدد في البند 8-1 (8). تعتبر أي رسوم مرتبطة بالإرجاع المبكر مستحقة الدفع في الوقت الذي يؤكد فيه العميل على الإرجاع المبكر. كما تخضع المرتجعات المبكرة للشروط التالية:
 9-6-1 في حالة رغبة العميل في إعادة السيارة في تاريخ استحقاق الدفعة الشهرية التالية، فسيتم احتساب أي رسوم لعقوبة الإنهاء المبكر المطبقة على العميل.
 9-6-2 في حالة رغبة العميل في إعادة سيارة قبل تاريخ استحقاق الدفعة الشهرية التالية، فسوف يتحمل العميل (1) رسوم الإرجاع في منتصف الشهر؛ و (2) أي رسوم لعقوبة الإنهاء المبكر المطبقة. إذا كان العميل قد استخدم السيارة لمدة تزيد عن 30 يومًا، فسوف يُضاف رصيد أي أيام غير مستخدمة دفع العميل قيمتها بالفعل إلى المحفظة الرقمية الخاصة بالعميل عند إعادة السيارة بنجاح. إذا استخدم العميل السيارة لمدة تقل عن 30 يومًا، فلن يتم رد قيمة أي أيام غير مستخدمة إلى العميل أو لن تتم إضافتها إلى المحفظة الرقمية الخاصة بالعميل.
9-6-3  في حالة رغبة العميل في إعادة سيارة مستخدمة لمدة تصل إلى 15 يومًا بعد تاريخ استحقاق الدفعة الشهرية التالية، فسوف يتحمل العميل: (1) بشكل تناسبي، تكلفة عدد الأيام ما بين التاريخ الذي كان من المفترض أن تكون الدفعة الشهرية التالية مستحقة فيه والتاريخ الذي يرغب فيه العميل في إعادة السيارة؛ و(2) رسوم الإرجاع في منتصف الشهر؛ و (ج) أي رسوم لعقوبة الإنهاء المبكر المطبقة.
 9-6-4 في حالة رغبة العميل في إعادة سيارة بعد مرور أكثر من 15 يومًا من تاريخ استحقاق الدفعة الشهرية التالية، فسوف يتحمل العميل: (1) دفعة الإيجار للشهر التالي على النحو المحدد في طلب التأكيد و/أو اتفاقية استئجار السيارة؛ و(2) رسوم الإرجاع في منتصف الشهر؛ و (ج) أي رسوم لعقوبة الإنهاء المبكر المطبقة. ستُضاف قيمة أي أيام غير مستخدمة للشهر التالي في المحفظة الرقمية للعميل عند إعادة السيارة بنجاح.
 9-7 لتجنب الشك، يوافق العملاء ويقرون بأن أي أموال مستردة ستُضاف إلى المحفظة الرقمية للعميل وليس إلى الحساب المصرفي للعميل أو البطاقة الائتمانية.
 9-8 يجوز لشركة ليقو ، في أي وقت ودون سابق إنذار، استخدام أي رصيد في المحفظة الرقمية الخاصة بالعميل لتعويض أي مبالغ مستحقة السداد بموجب هذه الاتفاقية و/أو أي اتفاقية استئجار السيارة.
 9-9 يعفي العملاء صراحة شركة ليقو من أي وجميع المسؤوليات المتعلقة باستئجار السيارة. يوافق العملاء ويقرون بأن شركة ليقو ليست مسؤولة عن حل أي نزاعات بين العملاء والبائعين، سواء أكانت متعلقة بإلغاء حجز مؤكد أم تنفيذ أي تغييرات على حجز مؤكد، أم خلاف ذلك، وأن شركة ليقو تعفي نفسها من أي وجميع المسؤوليات في هذا الصدد. إذا كان لديك أي استفسار حول عمليات الإلغاء أو الحجوزات، يرجى الاتصال بنا على support@legao.com.sa أو عبر المنصة.
 9-10 يوافق العملاء ويقرون بأن دفعات الإيجار تخضع لاتفاقية استئجار السيارة ولا يجوز بأي حال من الأحوال أن تتحمل شركة ليقو المسؤولية عن استرداد دفعات الإيجار والرسوم الإضافية.
`,
    thirdPartyContentTitle: "10. محتوى الغير :",
    thirdPartyContent: ` 10-1 باستخدام الخدمة، سيتمكن العملاء من الوصول إلى محتوى الغير ويشكل استخدام العميل للخدمة موافقة شركة ليقو على تقديم محتوى الغير إلى ذلك العميل. كما يقر ويعترف العملاء بكل المسؤوليات ويتحملون كل المخاطر الناشئة عن استخدامهم لمحتوى الغير.
 10-2 كجزء من الخدمة، قد تزودك شركة ليقو بروابط ملائمة لمنصة (منصات) الغير بالإضافة إلى أشكال أخرى من محتوى الغير. ويتم توفير هذه الروابط على سبيل المُجاملة لمشتركي الخدمة. وليس لدينا سيطرة على منصات أو محتوى الغير أو العروض الترويجية أو المواد أو المعلومات أو السلع أو الخدمات المتاحة عليها. ونحن لسنا مسؤولين عن أي محتوى للغير يتم الوصول إليه من خلال منصتنا. إذا قررت ترك المنصة والوصول إلى محتوى الغير، فإنك تقوم بذلك على مسؤوليتك الخاصة وينبغي لك أن تدرك أن الشروط والأحكام والسياسات الخاصة بنا لم تعد مطبقة عليك.
 10-3 لا تصرح لك هذه الاتفاقية بتوزيع أي محتوى تابع للغير أو عرضه أو تقديمه علنًا أو إتاحته أو تغييره أو استخدامه بأي طريقة أخرى.
`,
    intellectualPropertyTitle: "11. الملكية الفكرية :",
    intellectualProperty: ` 11-1 تحتفظ شركة ليقو بملكية جميع حقوق الملكية الفكرية من أي نوع ذي صلة بالمنصة والخدمة، بما في ذلك حقوق الطبع والنشر المطبقة وبراءات الاختراع والعلامات التجارية وحقوق الملكية الأخرى. وقد تكون العلامات التجارية وعلامات الخدمة والرسومات والشعارات الأخرى المستخدمة فيما يتعلق بالمنصة والخدمة علامات تجارية خاصة بالغير. ولا تنقل هذه الاتفاقية منا إليك أي ملكية فكرية خاصة بشركة ليقو أو الملكية الفكرية الخاصة بالغير، وستظل جميع الحقوق والملكيات والمصالح المرتبطة بهذه الملكية (كما بين الأطراف) خاصة بنا بمفردنا. ونحتفظ بجميع الحقوق التي لم يتم منحها لك صراحة بموجب هذه الاتفاقية.
 11-2 على وجه التحديد، إن شركة ليقو legao.com.sa  وجميع العلامات التجارية الأخرى التي تظهر أو يتم عرضها أو استخدامها على المنصة من وقت لآخر أو كجزء من الخدمة هي علامات تجارية مسجلة لصالح شركة ليقو ولا يجوز نسخها أو تنزيلها أو إعادة إصدارها أو استخدامها أو تعديلها أو توزيعها بأي شكل من الأشكال دون إذن كتابي مسبق من شركة ليقو.
 11-3 إذا كنت تعتقد أن أي مادة موجودة لدى شركة ليقو أو مرتبطة بها تنتهك حقوق الطبع والنشر الخاصة بك، فيرجى إعلامنا. وسوف نُنهي وصول المستخدم إلى المنصة واستخدامه إذا تم اكتشاف وتحديد المستخدم، في ظل الظروف المناسبة، على أنه يرتكب انتهاكًا متكررًا لحقوق الطبع والنشر أو حقوق الملكية الفكرية الأخرى لشركة ليقو أو الآخرين دون الحصول على الحقوق والأذونات اللازمة.
`,
    emailsTitle: "12. مراسلات البريد الإلكتروني :",
    emails:
      "نستخدم البريد الإلكتروني والوسائل الإلكترونية للبقاء على اتصال بعملائنا. لأغراض تعاقدية، يوافق العملاء: (1) على تلقي المراسلات من شركة ليقو في شكل إلكتروني عبر عنوان البريد الإلكتروني الذي أرسلوه أو عبر المنصة؛ و (2) يوافقون كذلك على أن جميع الأحكام والشروط والاتفاقيات والإخطارات والإفصاحات والمراسلات الأخرى التي تقدمها شركة ليقو لهم إلكترونيًا تستوفي أي متطلبات قانونية قد تفي بها هذه المراسلات إذا كانت في صورة كتابية مادية أو تقليدية؛ و (3) دون الإخلال بالبند 12 (1) و12 (2)، يتعهد العملاء بالامتثال للبند 16-5 لأي أغراض إخطار.",
    terminatingContractTitle: "13. إنهاء التعاقد :",
    terminatingContract: ` 13-1 إذا كنت ترغب في إنهاء هذه الاتفاقية، فيمكنك ببساطة التوقف عن استخدام منصة شركة ليقو. وإذا كنت ترغب في حذف بيانات حسابك، فيرجى الاتصال بشركة ليقو على support@legao.com.sa أو عبر المنصة. سنحتفظ بمعلوماتك ونستخدمها عند الضرورة للوفاء بالتزاماتنا القانونية، وحل النزاعات، وإنفاذ اتفاقياتنا، وسوف نحذف ملفك الشخصي بالكامل إلى أقصى حد ممكن (إن أمكن).
 13-2 يجوز للمستخدمين حذف حساباتهم باستخدام المنصة أو التطبيق إذا لم يستخدموا حساباتهم للحصول على استئجار سيارة، أو بمجرد مرور 60 يومًا من الإعادة الناجحة لآخر سيارة استأجرها المستخدم، إذا كانوا قد حصلوا مسبقًا على استئجار سيارة. دون الإخلال بأي نص مخالف لذلك، يوافق المستخدمون ويقرون بأن شركة ليقو تحتفظ بالحق في تعطيل قدرة المستخدم على حذف حسابه إذا كان لدى المستخدم أي دفعات مستحقة السداد لصالح شركة ليقو أو أي بائع بموجب هذه الاتفاقية و/أو اتفاقية استئجار السيارة.
 13-3 يجوز لشركة ليقو إنهاء وصولك إلى كل أو أي جزء من المنصة في أي وقت بشكل فوري، بسبب أو بدون سبب، مع تقديم إخطار أو بدون ذلك.
 13-4 لا يؤثر إنهاء علاقتك مع شركة ليقو على علاقتك بأي بائع احتفظت به من خلال خدمة شركة ليقو. جميع الواجبات والالتزامات والمسؤوليات القانونية والتعاقدية والأخلاقية تبقى سارية بعد إنهاء علاقة شركة ليقو.
 13-5 ستبقى جميع أحكام هذه الاتفاقية، التي يجب أن تظل نافذة المفعول بطبيعتها بعد الإنهاء، سارية بما في ذلك، على سبيل المثال لا الحصر، أحكام الملكية وإخلاء المسؤولية عن الضمانات والتعويضات وحدود المسؤولية.
`,
    disclaimerOfWarrantiesTitle: "14. إخلاء المسؤولية عن الضمانات :",
    disclaimerOfWarranties: ` 14-1 لا تقدم شركة ليقو أي إقرار أو ضمان بأن المعلومات التي نقدمها أو المقدمة من خلال الخدمة تعتبر دقيقة أو موثوق بها أو صحيحة؛ أو أن الخدمة ستفي بمتطلباتك؛ أو أن الخدمة ستكون متاحة في أي وقت أو موقع معين، أو أن الخدمة ستعمل بطريقة غير منقطعة أو ستكون آمنة؛ أو أنه سيتم تصحيح أي عيوب أو أخطاء؛ أو أن الخدمة خالية من الفيروسات أو العناصر الضارة الأخرى. إنك تتحمل المسؤولية كاملةً والمخاطر التي تنشأ عن الخسارة الناتجة عن استخدامك للمعلومات أو المحتوى أو المواد الأخرى التي تم الحصول عليها من البائع أو الخدمة.
 14-2 إنك وحدك المسؤول عن جميع مراسلاتك واتصالاتك مع البائعين، حسب الاقتضاء، ومع الأشخاص الآخرين الذين تتواصل معهم أو تتفاعل معهم نتيجة لاستخدامك للخدمات. إنك تدرك بأنه ليس مطلوبًا من شركة ليقو تفقد أو التقصي حول خلفية أي بائعين أو استئجار سيارة، ولا تقوم شركة ليقو بأي محاولة للتحقق من صحة بيانات البائعين. كما لا تقدم شركة ليقو أي إقرارات أو ضمانات بشأن تنفيذ استئجار السيارة. لا تتحكم شركة ليقو ولا تضمن وجود أو جودة أو صحة أو سلامة أو قانونية أي استئجار للسيارة يعلن عنه البائعون؛ أو قدرة البائعين على تنفيذ استئجار السيارة؛ أو أن خدمة البائع ستكون متاحة في أي وقت أو موقع معين. ولا تتعهد شركة ليقو أو تضمن أن أي استئجار سيارة تم عرضه من خلال المنصة سيفي بمتطلبات العميل. وإنك توافق على اتخاذ احتياطات معقولة في جميع المراسلات والاتصالات المنفذة مع البائعين، ومع الأشخاص الآخرين الذين تتواصل أو تتفاعل معهم نتيجة لاستخدامك للخدمات، خاصةً إذا قررت التواصل عبر وسائل أخرى غير الخدمات أو المقابلة الشخصية.
`,
    insemnificationAndCompensationTitle: "15. الإعفاء و التعويض :",
    insemnificationAndCompensation: ` 15-1 إنك توافق على تعويض وإبراء ذمة شركة ليقو وحمايتها من الضرر ضد أي وجميع المطالبات والطلبات والإجراءات والخسائر والأضرار والتقييمات والرسوم والمطلوبات والتكاليف والنفقات (بما في ذلك على سبيل المثال لا الحصر، أتعاب المحامين أو العقوبات أو الفوائد أو خسارة الأرباح) المقدمة من قبل البائع أو أي من الغير والتي قد يتم تحملها أو تكبدها في أي وقت من قبل شركة ليقو أو يتم تقييم ذلك ضدها، بشكل مباشر أو غير مباشر، نتيجة : (1) لاستخدامك للمنصة والخدمة أو انتهاكك هذه الاتفاقية أو العلاقة التعاقدية (أو نتيجة لإنهاء هذه العلاقة التعاقدية) بينك وبين البائع؛ أو (2) أي إصابة، أو حادث، أو تلف مادي أو تلف في الممتلكات، أو خسارة في الأرباح، أو خسارة في الممتلكات أو السمعة التجاري أو غير ذلك قد تتسبب فيه نتيجة لاستخدام أي خدمة و/أو استئجار سيارة؛ أو (3) حالات الخلل أو الأخطاء أو عدم الدقة في محتوى المستخدم الخاص بك و/أو المعلومات المتاحة على أو من خلال المنصة، أو (4) وصولك غير المصرح به إلى خوادمنا و/أو أي معلومات شخصية مخزنة فيها أو استخدامها، و/أو أي انقطاع أو توقف للإرسال إلى أو من خوادمنا، و/أو أي أعطال أو فيروسات أو أحصنة طروادة أو ما شابه ذلك، والتي قد تُرسلها إلى أو من خلال المنصة، و/أو (5) الإخفاق أو التأخير في تنفيذ أي معاملات من خلال المنصة و/أو الخدمات أو (6) نزاع أو تضارب أو خلاف بين المستخدمين فيما يتعلق بأي استئجار لسيارة أو دفعة إيجار أو رسوم إضافية أو إلغاء أي حجز مؤكد أو استئجار سيارة،؛ أو (7) التخلف عن التأكد من أن البائع مرخص قانونًا في المملكة العربية السعودية وحاصل على الموافقات الحكومية المطلوبة لأداء خدمات البائع.
 15-2 إذا كان لديك نزاع مع بائع واحد أو أكثر، فإنك تعفي شركة ليقو من أي وجميع المطالبات والطلبات والأضرار (الفعلية واللاحقة) أو الخسائر من كل نوع وطبيعة، الناشئة عن هذه النزاعات.
 15-3 يوافق العميل على أن شركة ليقو وكل بائع يتمتعان -على سبيل التضامن والتكافل - بسلطة رفع دعاوى قضائية ضد العميل ومتابعتها فيما يتعلق بأي مطالبات وطلبات وإجراءات وخسائر وأضرار وغرامات ورسوم ومطلوبات وتكاليف ونفقات تم تكبدها أو تحملها من قبل شركة ليقو و/أو البائع، بشكل مباشر أو غير مباشر، والتي سببها العميل نتيجة لاستخدام العميل لأي خدمة و/أو استئجار سيارة.
 15-4 يوافق العميل كذلك على أنه في حالة حصول البائع على حكم قضائي لصالحه فيما يتعلق بدعوى قضائية ضد شركة ليقو فيما يتعلق بأي مطالبات أو خسائر أو أضرار أو غرامات أو رسوم تسبب فيها العميل، فيحق لشركة ليقو رفع دعوى قضائية ضد العميل واسترداد أي مبلغ كان يتعين على شركة ليقو دفعه للبائع نتيجة للدعوى الأصلية التي رفعها البائع ضد شركة ليقو.
 15-5 إنك توافق على أنه لن تكون شركة ليقو -بأي حال من الأحوال- ملزمة أو مسؤولة أو غير ذلك تجاهك أو تجاه الغير عن أي أضرار أو خسائر قد تنشأ عن: (1) تعطل أو انقطاع أو توقف أي خدمة للحفاظ على وصولك إلى المنصة أو الخدمات، بغض النظر عما إذا كانت الخدمة مقدمة من شركة ليقو أو الغير أو (2) الجودة أو الدقة أو التوقيت المناسب أو السرعة أو الموثوقية أو أداء أي بائع أو خدمة بائع أو استئجار سيارة و/أو المنصة أو الاكتمال أو التأخيرات أو الخرق أو التقصيرات أو الانقطاعات في توفير خدمة استئجار سيارة أو خدمات البائع (بما في ذلك على سبيل المثال لا الحصر، أي خرق مرتكب من قبل البائع لأي التزام) أو (3) الأعطال أو الأخطاء أو عدم دقة أي محتوى و/أو معلومات متوافرة على أو من خلال المنصة، أو (4) أي وصول غير مصرح به إلى خوادمنا و/أو أي وجميع المعلومات الشخصية المخزنة فيها أو استخدامها، و/أو أي انقطاع أو وقف للإرسال إلى خوادمنا و/أو أي أخطاء أو فيروسات أو أحصنة طروادة أو ما شابه ذلك، والتي قد يتم نقلها إلى أو من خلال المنصة بواسطة أي من الغير، و/أو (5) أي إخفاق أو تأخير في تنفيذ أي معاملات من خلال المنصة و/أو الخدمات أو، ( 6) أي نزاع أو تضارب أو خلاف بين المستخدمين فيما يتعلق بأي خدمات أو استئجار سيارة أو دفعة إيجار أو رسوم إضافية أو إلغاء أي حجز مؤكد أو استئجار سيارة؛ أو (7) أي دفعة مستردة أو خسارة في الأرباح أو فقدان للسمعة التجارية (سواء تم تكبدها بشكل مباشر أو غير مباشر) أو أي إصابة أو حادث أو تلف مادي أو في الممتلكات أو مشكلات صحية أو غير ذلك قد يلحق بالعميل نتيجة لاستخدام أي خدمة بائع.
`,
    miscellaneousProvisionsTitle: "16. أحكام متفرقة :",
    miscellaneousProvisions: ` 16-1 القانون الحاكم: تخضع هذه الاتفاقية المبرمة بين العميل وشركة ليقو وأي وصول إلى أو استخدام العميل للمنصة أو الخدمة لقوانين ولوائح المملكة العربية السعودية. تتم تسوية أي نزاع قد ينشأ بين العميل وشركة ليقو فيما يتعلق بتنفيذ أو تفسير هذه الاتفاقية بطريقة ودية، وفي حالة عدم التمكن من ذلك، فتعتبر محاكم جدة هي السلطة المختصة لتسوية ذلك.
 16-2 القابلية للفصل: إذا تم اعتبار أي جزء من هذه الاتفاقية غير صالح أو غير قابل للإنفاذ، فسيتم تفسير ذلك الجزء من الاتفاقية على أنه يعكس النية الأصلية للطرفين. وستبقى الأجزاء المتبقية سارية المفعول بكامل الأثر والنفاذ. لن يعتبر أي تخلف من جانب شركة ليقو عن إنفاذ أي نص من نصوص هذه الاتفاقية تنازلاً عن حقنا في إنفاذ هذا النص. وستظل حقوقنا بموجب هذه الاتفاقية سارية بعد أي إنهاء لهذه الاتفاقية.
 16-3 القابلية للتنازل: يجوز لشركة ليقو التنازل عن أو تفويض حقوقها أو التزاماتها بموجب هذه الشروط والأحكام و/أو سياسة خصوصية شركة ليقو ، كليًا أو جزئيًا، إلى أي شخص أو كيان في أي وقت بموافقتك أو بدونها. لا يجوز لك التنازل عن أو تفويض أي من حقوقك أو التزاماتك بموجب الأحكام والشروط أو سياسة الخصوصية دون الحصول على موافقة كتابية مسبقة من شركة ليقو ، ويُعتبر أي تنازل وتفويض غير مصرح به مقدم من قِبلك لاغيًا وباطلاً.
 16-4 الإخطارات الصادرة للعملاء: قد ترسل شركة ليقو إلى العملاء التقارير والبيانات والإخطارات وأي مراسلات أخرى عبر عنوان البريد الإلكتروني الذي يحددونه في حساباتهم. كما سيتم اعتبار جميع المراسلات والإخطارات صادرة ومرسلة للعميل على النحو الواجب عند إرسالها إلكترونيًا بواسطة شركة ليقو إلى العميل إلى عنوان البريد الإلكتروني المحدد في حساب العميل.
 16-5 إخطارات شركة ليقو : يمكن للعميل إرسال التقارير والبيانات والإخطارات وأي مراسلات أخرى إلى شركة ليقو على بريد الشركة الالكتروني info@leago.org وتعتبر جميع المراسلات والإخطارات مستلمة أو مقدمة (حسب الاقتضاء) إلى شركة ليقو عند تلقيها إلكترونيًا بواسطة شركة ليقو على info@leago.org
 16-6 العناوين: العناوين والتسميات التوضيحية الواردة في هذه الاتفاقية ذُكرت على سبيل التيسير فقط ولكنها لا تحدد أو تصف -بأي شكل من الأشكال- نطاق أو محتوى أي حكم من أحكام هذه الاتفاقية.
 16-7 المُخاطب المُحايد: حيثما استخدم في هذه الوثيقة وحسب ما يقتضيه السياق، يجب أن يتضمن العدد المفرد صيغة الجمع، ويجب أن يتضمن الجمع صيغة المفرد، واستخدام أي من الجنسين يجب أن يشمل كلا النوعين وكلمات "من هذه الوثيقة" و "في هذه الوثيقة" و"فيما بعد" تشير إلى لاتفاقية بأكملها وليس إلى أي نص أو قسم.
إنك تقر بأنك قرأت وفهمت وقبلت الالتزام بهذه الشروط والأحكام.
`,
  },
};

export const contactUs = {
  en: {
    pageTitle: "Contact Us",
    whatsappChat: "Chat with our Customer Service",
    email: "Email our Customer Service",
  },
  ar: {
    pageTitle: "تواصل معنا",
    whatsappChat: "للتحدث إلى خدمة العملاء",
    email: "المراسلة عبر البريد الإلكتروني",
  },
};
